config/routes.rb
Rails.application.routes.draw do

  devise_for :employees,
    path: '',
    path_names: { sign_in: 'login', sign_out: 'logout' }

  # Sets the 'index' action in the Times controller as the home page.
  root 'times#index'

  get 'week/:start_of_week', to: 'times#week', as: :calendar_week
  get 'sick-day/:date', to: 'times#mark_sick_day', as: :mark_sick_day

  post 'check-in', to: 'check_ins#check_in', as: :check_in
  post 'check-out', to: 'check_ins#check_out', as: :check_out

  resources :employees
  get 'employees/:id/:start_of_week', to: 'employees#week', as: :employee_calendar_week
  post 'employees/:id/deactivate-employee', to: 'employees#deactivate_employee', as: :deactivate_employee
  patch 'employees/:id/deactivate-employee', to: 'employees#deactivate_employee'

  resources :employee_holidays, path: 'holidays'

  resources :holiday_requests,  path: 'holiday-requests'
  get 'holiday-requests/:id/approve', to: 'holiday_requests#approve', as: :approve_holiday_request
  get 'holiday-requests/:id/decline', to: 'holiday_requests#decline', as: :decline_holiday_request

  resources :company_holidays, path: 'company-holidays'

  get 'calendar', to: 'calendar#index', as: :calendar
  get 'calendar/:date', to: 'calendar#month', as: :calendar_date

  # resources :times, only: %i(edit_check_in edit_check_out)
  patch 'times/:id/edit/check-in', to: 'times#edit_check_in', as: :edit_time_check_in
  patch 'times/:id/edit/check-out', to: 'times#edit_check_out', as: :edit_time_check_out
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  include HolidaysHelper

  IMAGE_MISSING_PATH = 'missing.jpg'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Rails relation that links the CheckIn model to Employees
  has_many :check_ins
  has_many :sick_days
  has_many :holiday_requests

  # Validations
  validates :email,                          presence: true
  validates :first_name,                     presence: true
  validates :last_name,                      presence: true
  validates :job_title,                      presence: true
  validates :start_date,                     presence: true
  validates :date_of_birth,                  presence: true
  validates :contracted_hours,               presence: true
  validates :emergency_contact_name,         presence: true
  validates :emergency_contact_relation,     presence: true
  validates :emergency_contact_phone_number, presence: true

  has_attached_file :avatar, default_url: IMAGE_MISSING_PATH

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  # Build in rails method that specifies how the parameter for the Model will
  # appear in URLs e.g.:
  #
  #   /employees/1-tim-green
  #
  # @returns (String) - URL parameter
  def to_param
    [id, full_name.parameterize].join('-')
  end

  # Returns full name of employee
  #
  # @returns (String) - full name
  def full_name
    "#{first_name} #{last_name}"
  end

  # More readable method to return the active value
  #
  # @returns (Boolean) - Employee.active
  def is_active?
    active
  end

  # Returns an Employee model of the line manager of self.
  #
  # @returns (Employee) - the line manager of self, if one is set
  def line_manager
    line_manager_id.nil? ? nil : Employee.find(line_manager_id)
  end

  def subordinates
    Employee.where(line_manager_id: id)
  end

  def check_in
    check_ins.create(check_in_time: Time.now)
  end

  def check_out
    check_in = check_ins.order(:check_in_time).last

    # If the user is checking out a day after they checked in, they must have
    # forgotten to check out so it changes check-out time to the end of the
    # previous day, allowing them to change it as needed.
    if Time.at(Time.now).to_date === Time.at(check_in.check_in_time).to_date
      check_out_time = Time.now
    else
      check_out_time = Time.at(check_in.check_in_time).to_date.end_of_day
    end

    check_in.update_attributes(check_out_time: check_out_time)
  end

  # Is self checked in currently
  #
  # @returns (Boolean)
  def checked_in?
    check_ins.any? && check_ins.order(:check_in_time).last.check_out_time.nil?
  end

  # Returns the total minutes checked in on date
  #
  # @param (Date) - the date the user was checked in
  # @returns (Integer) - total minutes checked in on date
  def minutes_checked_in_on_date(date)
    total_minutes = 0

    all_check_ins_on_date(date).each { |check_in| total_minutes += check_in.time_checked_in }

    total_minutes
  end

  # Returns the time self was checked in on a given date in the format:
  #  6h 36m
  #
  # @param (Date) - the date the user was checked in
  # @returns (String) - formatted time checked in
  def formatted_time_checked_in_on_date(date)
    total_minutes = minutes_checked_in_on_date(date)
    format_minutes(total_minutes)
  end

  # Returns the time self was checked in for whole week:
  #  6h 36m
  #
  # @param (Date) - start of week
  # @returns (String) - formatted time checked in for week
  def formatted_time_checked_in_on_week(date)
    week = (date..(date + 6)).to_a
    total_minutes = 0

    week.each { |day| total_minutes += minutes_checked_in_on_date(day) }

    format_minutes(total_minutes)
  end

  # Returns the largest number of CheckIns on any day of the current week
  #
  # @param (Date) - date of first day of the week
  # @returns (Integer) - on any given day of week, max number of check-ins
  def max_check_ins_on_week_starting(date)
    week = (date..(date + 6)).to_a

    max_check_ins = 0

    # loops over each day to find day with most check-ins
    week.each do |day|
      if all_check_ins_on_date(day).count > max_check_ins
        max_check_ins = all_check_ins_on_date(day).count
      end

      if (
        (max_check_ins == 0) &&
          (is_sick_day?(day) ||
          CompanyHoliday.is_holiday?(day) ||
          is_on_holiday?(day))
      )
        max_check_ins = 1
      end
    end

    max_check_ins
  end

  # Gets all CheckIns today
  def all_check_ins_today
    all_check_ins_on_date(Date.today)
  end

  # Gets all CheckIns from given date, including ones where user is currently
  # checked in
  #
  # @param (Date) - date of check-ins
  # @returns (Array) - array containing check-in models
  def all_check_ins_on_date(date)
    check_ins.where(
      # strings concatenated to make more readable and ensures it doesn't go off the page
      '(check_in_time >= ? AND check_in_time <= ?) AND ' +
      '((check_out_time <= ? AND check_out_time >= ? AND check_out_time is NOT NULL) OR ' +
      '(check_out_time is NULL)) ',
      date.to_date.beginning_of_day,
      date.to_date.end_of_day,
      date.to_date.end_of_day,
      date.to_date.beginning_of_day
    ).order(:check_in_time).to_a
  end

  # Does self have any check-ins on the week starting on the given date
  #
  # @returns (Boolean)
  def has_check_ins_on_week?(date)
    first_day = date.at_beginning_of_week
    current_week = (first_day..(first_day + 4)).to_a
    current_week.each { |day| return true if all_check_ins_on_date(day).any? }
    false
  end

  def can_view_next_week?(start_of_current_week)
    has_check_ins_on_week?(start_of_current_week + 7.days) ||
    start_of_current_week + 7.days <= Date.today
  end

  def can_view_previous_week?(start_of_current_week)
    has_check_ins_on_week?(start_of_current_week - 7.days) ||
    start_date <= start_of_current_week - 3.days
  end

  # Can the Employee check in on the given date?
  #
  # @returns (Booelean)
  def can_check_in?(date)
    !is_on_holiday?(date) &&
    !is_sick_day?(date) &&
    !is_company_holiday?(date)
  end

  # Calculates the amount of holiday days per year the employee gets
  #
  # @returns (Integer)
  def allocated_holiday_days
    standard_number_of_days = 25

    # for every year, add another day, up to 35 days
    years_at_company = Time.now.year - start_date.year

    return 35 if standard_number_of_days + years_at_company >= 35

    standard_number_of_days + years_at_company
  end

  # Calculates the remaining holiday days the employee has this year
  #
  # @returns (Integer)
  def remaining_holiday_days
    count = 0

    approved_holiday_requests.each do |request|
      request.employee_holidays.each do |holiday|
        count += 1 if holiday.date.year == Date.today.year
      end
    end

    allocated_holiday_days - count
  end

  # Calculates whether the employee can mark the given day as a sick day
  #
  # @returns (Boolean)
  def can_mark_as_sick_day?(day)
    Date.today >= day &&
    !is_sick_day?(day) &&
    !is_company_holiday?(day) &&
    !is_on_holiday?(day) &&
    !all_check_ins_on_date(day).any?
  end

  # Is the given day a sick day?
  #
  # @returns (Boolean)
  def is_sick_day?(date)
    sick_days.where(date: date).any?
  end

  # Returns all holiday requests that have not been approved
  #
  # @returns (ActiveRecord::Relation)
  def unapproved_holiday_requests
    self.holiday_requests.where(
      "authorised = ? AND authorised_by_id IS NOT NULL",
      false
    )
  end

  # Returns all holiday requests that have been approved
  #
  # @returns (ActiveRecord::Relation)
  def approved_holiday_requests
    self.holiday_requests.where(authorised: true)
  end

  def declined_holiday_requests
    self.holiday_requests.where(
      "authorised = ? AND authorised_by_id IS NOT NULL",
      false
    )
  end

  def pending_holiday_requests
    self.holiday_requests.where(
      "authorised = ? AND authorised_by_id IS NULL",
      false
    )
  end

  def pending_subordinate_holiday_requests
    requests = []

    subordinates.each do |subordinate|
      if (pending_requests = subordinate.pending_holiday_requests.to_a).count > 0
        requests << pending_requests
      end
    end

    requests.flatten
  end

  # Does the employee has enough holiday days remaining to book a holiday in
  # the date range given?
  #
  # @returns (Boolean)
  def has_enough_holiday_left?(date_range)
    calculate_holidays_used(date_range) <= remaining_holiday_days
  end

  def is_allowed_date_off?(date)
    # Methods found in HolidaysHelper
    !is_weekend?(date) &&
    !is_company_holiday?(date) &&
    !will_be_understaffed?(self, date) &&
    !is_on_holiday?(date)
  end

  # Is the employee on holiday on the given date?
  #
  # @returns (Boolean)
  def is_on_holiday?(date)
    approved_holiday_requests.each do |request|
      request.employee_holidays.each do |holiday|
        return true if holiday.date == date
      end
    end

    false
  end

  # Is the given date the birthday of the employee?
  #
  # @returns (Boolean)
  def is_birthday?(date)
    date_of_birth.day == date.day &&
    date_of_birth.month == date.month
  end

  # Has the employee set an avatar
  #
  # @returns (Boolean)
  def has_avatar?
    avatar.url != IMAGE_MISSING_PATH
  end

  def check_in_out_times(week)
    check_in_out_times = [] # array used to populate time table

    week.each_with_index do |day, i|
      check_in_out_times[i] = []

      all_check_ins_on_date(day).each do |check_in|
        check_in_out_times[i].push(check_in)
      end
    end

    check_in_out_times
  end

  # Returns age of employee
  #
  # @returns (Integer)
  def age
    now = Time.now.utc.to_date
    now.year - date_of_birth.year - (date_of_birth.to_date.change(year: now.year) > now ? 1 : 0)
  end

  def address

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_employee!
  before_action :authenticate_line_manager!

  def index
    @employees = Employee.all.order(
      active: :desc,
      last_name: :asc,
      first_name: :asc
    )

    @start_of_week = Date.today.at_beginning_of_week
    @end_of_week = @start_of_week + 6.days
    @week = @start_of_week..@end_of_week
  end

  def week
    @employees = Employee.all.order(
      active: :desc,
      last_name: :asc,
      first_name: :asc
    )

    @employee = Employee.find(params[:id])
    set_week_variables @employee

    render :show
  end

  def show
    @employee = Employee.find(params[:id])
    set_week_variables @employee
  end

  def new
    @employee = Employee.new
    @potential_line_manager = Employee.where(active: true, is_line_manager: true)
  end

  def create
    @employee = Employee.new(employee_params.merge({ password: 'password' }))
    @potential_line_manager = Employee.where(active: true, is_line_manager: true)

    if @employee.save
      flash[:success] = "Employee saved! Their password is 'password', please encourage them to change this!"
      redirect_to @employee
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
    @potential_line_manager = Employee.where(active: true, is_line_manager: true)
  end

  def update
    @employee = Employee.find(params[:id])
    @potential_line_manager = Employee.where(active: true, is_line_manager: true)

    if @employee.update_attributes(employee_params)
      flash[:success] = 'Employee updated'
      redirect_to @employee
    else
      render :edit
    end
  end

  def deactivate_employee
    employee = Employee.find(params[:id])
    end_date = Date.parse(params[:employee][:end_date])

    if employee.update_attributes(active: false, end_date: end_date)
      flash[:success] = 'Employee Deactivated'
    else
      flash[:danger] = 'Error deactivating employee'
    end

    redirect_to employee
  end

  private

    def employee_params
      params.require(:employee).permit(:email, :first_name, :last_name,
        :address_line_1, :address_line_2, :post_code, :contracted_hours,
        :line_manager_id, :start_date, :job_title, :is_line_manager,
        :emergency_contact_name, :emergency_contact_relation,
        :emergency_contact_phone_number, :emergency_contact_phone_number_2,
        :date_of_birth, :avatar)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
  def user_card_class_helper(employee)
    'deactivated' unless employee.is_active?
  end
end

app/views/employees/_deactivate_employee_modal.html.haml
#deactivate_employee_modal.modal.fade{ 'aria-labelledby' => 'myModalLabel', role: :dialog, tabindex: '-1' }
  .modal-dialog{ role: 'document' }
    .modal-content
      .modal-header
        %button.close{ 'aria-label' => 'Close', 'data-dismiss' => 'modal', type: :button }
          %span{ 'aria-hidden' => 'true' } ×
        %h4.modal-title Modal title
      .modal-body
        = form_for(@employee, url: deactivate_employee_path) do |f|
          .form-group
            = f.label :end_date, 'Date of Leaving'
            = f.text_field :end_date, class: 'form-control employee-termination-date', id: 'datepicker'

          .form-group
            %button.btn.btn-default{ 'data-dismiss' => 'modal', type: :button } Close
            = f.submit 'Save changes', class: 'btn btn-primary pull-right'

app/views/employees/edit.html.haml
- provide :title, 'Edit Employee'

.panel.panel-default.new-employee-form
  .panel-heading Create a new Employee
  .panel-body
    = form_for(@employee) do |f|
      = render 'shared/error_messages', object: f.object

      %h3.new-employee-form__subtitle Personal Details

      .row
        .col-md-6
          .form-group
            = f.label :email, class: 'control-label'
            = f.email_field :email, class: 'form-control', autofocus: true
          .row
            .form-group.col-md-6
              = f.label :first_name, 'First Name', class: 'control-label'
              = f.text_field :first_name, class: 'form-control'
            .form-group.col-md-6
              = f.label :last_name, 'Last Name', class: 'control-label'
              = f.text_field :last_name, class: 'form-control'
          .form-group
            = f.label :date_of_birth, 'Date of Birth', class: 'control-label'
            = f.date_field :date_of_birth, class: 'form-control'
        .col-md-6
          .form-group
            = f.label :address_line_1, 'Address Line 1', class: 'control-label'
            = f.text_field :address_line_1, class: 'form-control'
          .form-group
            = f.label :address_line_2, 'Address Line 2', class: 'control-label'
            = f.text_field :address_line_2, class: 'form-control'
          .form-group
            = f.label :post_code, 'Post Code', class: 'control-label'
            = f.text_field :post_code, class: 'form-control'

      %h3.new-employee-form__subtitle Employment Details

      .row
        .col-md-6
          .form-group
            = f.label :contracted_hours, 'Contracted Hours', class: 'control-label'
            = f.text_field :contracted_hours, class: 'form-control'
          .form-group
            = f.label :line_manager_id, 'Line Manager', class: 'control-label'
            = f.collection_select :line_manager_id, @potential_line_manager, :id, :full_name, { include_blank: 'Choose a line manager...' }, { class: 'form-control' }
          .form-group
            = f.label :start_date, 'Start Date', class: 'control-label'
            = f.date_field :start_date, class: 'form-control'
        .col-md-6
          .form-group
            = f.label :job_title, 'Job Title', class: 'control-label'
            = f.text_field :job_title, class: 'form-control'
          .form-group
            = f.label :is_line_manager, 'Is Employee a Line Manager?', class: 'control-label'
            = f.check_box :is_line_manager, class: 'form-control'

      %h3.new-employee-form__subtitle Emergency Contacts

      .row
        .col-md-6
          .form-group
            = f.label :emergency_contact_name, 'Emergency Contact Name', class: 'control-label'
            = f.text_field :emergency_contact_name, class: 'form-control'
          .form-group
            = f.label :emergency_contact_relation, 'Emergency Contact Relation', class: 'control-label'
            = f.text_field :emergency_contact_relation, class: 'form-control'

        .col-md-6
          .form-group
            = f.label :emergency_contact_phone_number, 'Emergency Contact Phone Number', class: 'control-label'
            = f.text_field :emergency_contact_phone_number, class: 'form-control'
          .form-group
            = f.label :emergency_contact_phone_number_2, 'Emergency Contact Phone Number (other)', class: 'control-label'
            = f.text_field :emergency_contact_phone_number_2, class: 'form-control'

      = f.submit 'Update Employee', class: 'btn btn-default pull-right'

app/views/employees/index.html.haml
- provide :title, 'Employees'

.pull-right
  = link_to new_employee_path, class: 'btn btn-primary btn-new-employee' do
    %span.glyphicon.glyphicon-plus
    Add New Employee

%h1 Employees

.row.user-card__container
  - @employees.each do |employee|
    .panel.panel-default.user-card{ class: user_card_class_helper(employee) }

      .user-card__body
        - if employee.is_active?
          = render 'shared/time_table/table', employee: employee
        - else
          %h2.user-card__deactivated Deactivated

      .user-card__side-panel
        = link_to employee do
          = image_tag employee.avatar.url, class: 'user-card__photo'
        %h4.user-card__name
          %span.user-card__full_name= link_to employee.full_name, employee
          - if employee.job_title.downcase == 'director'
            %br
            %span.label.label-default.user-card__director-label DIRECTOR
          - else
            %small.user-card__job-title= employee.job_title

        %ul.user-card__details
          - if employee.line_manager
            %li
              %strong Reports to:
              = link_to employee.line_manager.full_name, employee.line_manager
          %li
            %strong Hours per week:
            = employee.contracted_hours

      .panel-footer.user-card__footer

        %ul.user-card__footer--links
          %li

app/views/employees/new.html.haml
- provide :title, 'New Employee'

.panel.panel-default.new-employee-form
  .panel-heading Create a new Employee
  .panel-body
    = form_for(@employee) do |f|
      = render 'shared/error_messages', object: f.object

      %h3.new-employee-form__subtitle Personal Details

      .row
        .col-md-6
          .form-group
            = f.label :email, class: 'control-label'
            = f.email_field :email, class: 'form-control', autofocus: true
          .row
            .form-group.col-md-6
              = f.label :first_name, 'First Name', class: 'control-label'
              = f.text_field :first_name, class: 'form-control'
            .form-group.col-md-6
              = f.label :last_name, 'Last Name', class: 'control-label'
              = f.text_field :last_name, class: 'form-control'
          .form-group
            = f.label :date_of_birth, 'Date of Birth', class: 'control-label'
            = f.date_field :date_of_birth, class: 'form-control'
        .col-md-6
          .form-group
            = f.label :address_line_1, 'Address Line 1', class: 'control-label'
            = f.text_field :address_line_1, class: 'form-control'
          .form-group
            = f.label :address_line_2, 'Address Line 2', class: 'control-label'
            = f.text_field :address_line_2, class: 'form-control'
          .form-group
            = f.label :post_code, 'Post Code', class: 'control-label'
            = f.text_field :post_code, class: 'form-control'

      %h3.new-employee-form__subtitle Employment Details

      .row
        .col-md-6
          .form-group
            = f.label :contracted_hours, 'Contracted Hours', class: 'control-label'
            = f.text_field :contracted_hours, class: 'form-control'
          .form-group
            = f.label :line_manager_id, 'Line Manager', class: 'control-label'
            = f.collection_select :line_manager_id, @potential_line_manager, :id, :full_name, { include_blank: 'Choose a line manager...' }, { class: 'form-control' }
          .form-group
            = f.label :start_date, 'Start Date', class: 'control-label'
            = f.date_field :start_date, class: 'form-control'
        .col-md-6
          .form-group
            = f.label :job_title, 'Job Title', class: 'control-label'
            = f.text_field :job_title, class: 'form-control'
          .form-group
            = f.label :is_line_manager, 'Is Employee a Line Manager?', class: 'control-label'
            = f.check_box :is_line_manager, class: 'form-control'

      %h3.new-employee-form__subtitle Emergency Contacts

      .row
        .col-md-6
          .form-group
            = f.label :emergency_contact_name, 'Emergency Contact Name', class: 'control-label'
            = f.text_field :emergency_contact_name, class: 'form-control'
          .form-group
            = f.label :emergency_contact_relation, 'Emergency Contact Relation', class: 'control-label'
            = f.text_field :emergency_contact_relation, class: 'form-control'

        .col-md-6
          .form-group
            = f.label :emergency_contact_phone_number, 'Emergency Contact Phone Number', class: 'control-label'
            = f.text_field :emergency_contact_phone_number, class: 'form-control'
          .form-group
            = f.label :emergency_contact_phone_number, 'Emergency Contact Phone Number (other)', class: 'control-label'
            = f.text_field :emergency_contact_phone_number_2, class: 'form-control'

      = f.submit 'Create Employee', class: 'btn btn-default pull-right'

app/views/employees/show.html.haml
- provide :title, @employee.full_name

- unless @employee.active
  .alert.alert-info{ role: alert }
    This employee left Parallax on
    = succeed '.' do
      = @employee.end_date.strftime("%a #{@employee.end_date.day.ordinalize} %B %Y")

- if @employee.active
  .pull-right
    = link_to 'Deactivate Employee', '#', class: 'btn btn-danger btn-deactivate-employee', data: { toggle: 'modal', target: '#deactivate_employee_modal' }

= render 'employees/deactivate_employee_modal'

.row
  .col-md-3
    = render 'shared/small_user_card', employee: @employee
  .col-md-9.employee-show__table-container
    %h5.center.week-starting
      .row
        .col-md-3.previous-week
          - if current_employee.can_view_previous_week?(@start_of_week)
            = link_to 'previous week', employee_calendar_week_path(@employee, @start_of_week - 7.days), class: 'btn btn-primary'
          - else
            = link_to 'previous week', employee_calendar_week_path(@employee, @start_of_week - 7.days), class: 'btn btn-disabled', disabled: ''

        .col-md-6.current-week
          = @start_of_week.strftime("%a #{@start_of_week.day.ordinalize} %B")
          &mdash;
          = @end_of_week.strftime("%a #{@end_of_week.day.ordinalize} %B")
          %br
          = surround '(', ')' do
            = @start_of_week.strftime("%-d/%-m/%Y")
            &mdash;
            = @end_of_week.strftime("%-d/%-m/%Y")

        .col-md-3.next-week
          - if current_employee.can_view_next_week?(@start_of_week)
            = link_to 'next week', employee_calendar_week_path(@employee, @start_of_week + 7.days), class: 'btn btn-primary'
          - else
            = link_to 'next week', employee_calendar_week_path(@employee, @start_of_week + 7.days), class: 'btn btn-disabled', disabled: ''

    = render 'shared/time_table/table', employee: @employee

    .panel.panel-default.new-employee-form
      .panel-heading
        .pull-right= link_to 'Edit', edit_employee_path(@employee)
        Details
      .panel-body
        .row
          .col-md-6
            %form.form-horizontal
              .form-group
                %label.col-sm-3.control-label Email
                .col-sm-9
                  %p.form-control-static= link_to @employee.email, "mailto:#{@employee.email}"
              .form-group
                %label.col-sm-3.control-label Address
                .col-sm-9
                  %p.form-control-static= @employee.address
          .col-md-6
            %form.form-horizontal
              .form-group
                %label.col-sm-3.control-label D.O.B.
                .col-sm-9
                  %p.form-control-static
                    = @employee.date_of_birth.strftime("%-d/%-m/%Y")
                    = surround '(', ')' do
                      = @employee.age
      %hr
        .row
          .col-md-6
            %form.form-horizontal
              .form-group
                %label.col-sm-3.control-label Job Title
                .col-sm-9
                  %p.form-control-static
                    = @employee.job_title
          .col-md-6
            %form.form-horizontal
              .form-group
                %label.col-sm-3.control-label Contracted Hours
                .col-sm-9
                  %p.form-control-static
                    = @employee.contracted_hours