config/routes.rb
Rails.application.routes.draw do

  devise_for :employees,
    path: '',
    path_names: { sign_in: 'login', sign_out: 'logout' }

  # Sets the 'index' action in the Times controller as the home page.
  root 'times#index'

  get 'week/:start_of_week', to: 'times#week', as: :calendar_week
  get 'sick-day/:date', to: 'times#mark_sick_day', as: :mark_sick_day

  post 'check-in', to: 'check_ins#check_in', as: :check_in
  post 'check-out', to: 'check_ins#check_out', as: :check_out

  resources :employees
  get 'employees/:id/:start_of_week', to: 'employees#week', as: :employee_calendar_week
  post 'employees/:id/deactivate-employee', to: 'employees#deactivate_employee', as: :deactivate_employee
  patch 'employees/:id/deactivate-employee', to: 'employees#deactivate_employee'

  resources :employee_holidays, path: 'holidays'

  resources :holiday_requests,  path: 'holiday-requests'
  get 'holiday-requests/:id/approve', to: 'holiday_requests#approve', as: :approve_holiday_request
  get 'holiday-requests/:id/decline', to: 'holiday_requests#decline', as: :decline_holiday_request

  resources :company_holidays, path: 'company-holidays'

  get 'calendar', to: 'calendar#index', as: :calendar
  get 'calendar/:date', to: 'calendar#month', as: :calendar_date

  # resources :times, only: %i(edit_check_in edit_check_out)
  patch 'times/:id/edit/check-in', to: 'times#edit_check_in', as: :edit_time_check_in
  patch 'times/:id/edit/check-out', to: 'times#edit_check_out', as: :edit_time_check_out
end

app/views/shared/_company_holiday.html.haml
.col-md-4
  .panel.panel-primary.holiday-panel
    .panel-heading.holiday-panel__heading
      - if current_employee.is_line_manager
        .pull-righ
          = link_to company_holiday_path(holiday), method: :delete, class: 'holiday-panel__delete-holiday', data: { confirm: 'Are you sure you want to delete this holiday?' } do
            delete
    .panel-body
      .row
        .col-md-12.holiday-panel__section
          - if holiday.christmas?
            .pull-right
              %span.glyphicon.glyphicon-tree-conifer.holiday-panel__christmas-tree
          %strong Date
          .holiday-panel__section--value= holiday.date.strftime("%a #{holiday.date.day.ordinalize} %B %Y")

app/views/shared/_employee_holiday_list.html.haml
.employee-holidays
  - @holiday_list_days.each do |date|
    - if any_employee_holidays_on_date?(date)
      %h6= date.strftime("%a #{date.day.ordinalize} %B")
      %ul.employee-holidays__list
        - EmployeeHoliday.on_date(date).each do |holiday|
          - if current_employee.is_line_manager
            %li= link_to holiday.holiday_request.employee.full_name, holiday.holiday_request.employee
          - else
            %li= holiday.holiday_request.employee.full_name

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error-explanation
    %span.alert.alert-danger
      %strong
        The form contains
        = pluralize(object.errors.count, "error")
    %ul.error-list
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/shared/_flash_notice.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key} alert-dissmissable", :role => "alert"}
    %button.close{"data-dismiss" => "alert", :type => "button"}
      %span{"aria-hidden" => "true"} ×
      %span.sr-only Close
    = value

app/views/shared/_small_user_card.html.haml
.user-card--small
  = image_tag(employee.avatar.url, class: 'user-card--small__photo')

  %h3.user-card--small__name
    = employee.full_name
    %small.user-card--small__job-title
      - if employee.job_title.downcase == 'director' && employee.is_line_manager
        %br
        %span.label.label-default.user-card__director-label DIRECTOR
      - else
        %small.user-card__job-title= employee.job_title