config/routes.rb
Rails.application.routes.draw do

  devise_for :employees,
    path: '',
    path_names: { sign_in: 'login', sign_out: 'logout' }

  # Sets the 'index' action in the Times controller as the home page.
  root 'times#index'

  get 'week/:start_of_week', to: 'times#week', as: :calendar_week
  get 'sick-day/:date', to: 'times#mark_sick_day', as: :mark_sick_day

  post 'check-in', to: 'check_ins#check_in', as: :check_in
  post 'check-out', to: 'check_ins#check_out', as: :check_out

  resources :employees
  get 'employees/:id/:start_of_week', to: 'employees#week', as: :employee_calendar_week
  post 'employees/:id/deactivate-employee', to: 'employees#deactivate_employee', as: :deactivate_employee
  patch 'employees/:id/deactivate-employee', to: 'employees#deactivate_employee'

  resources :employee_holidays, path: 'holidays'

  resources :holiday_requests,  path: 'holiday-requests'
  get 'holiday-requests/:id/approve', to: 'holiday_requests#approve', as: :approve_holiday_request
  get 'holiday-requests/:id/decline', to: 'holiday_requests#decline', as: :decline_holiday_request

  resources :company_holidays, path: 'company-holidays'

  get 'calendar', to: 'calendar#index', as: :calendar
  get 'calendar/:date', to: 'calendar#month', as: :calendar_date

  # resources :times, only: %i(edit_check_in edit_check_out)
  patch 'times/:id/edit/check-in', to: 'times#edit_check_in', as: :edit_time_check_in
  patch 'times/:id/edit/check-out', to: 'times#edit_check_out', as: :edit_time_check_out
end

app/controllers/times_controller.rb
class TimesController < ApplicationController
  before_action :authenticate_employee!
  before_action :validate_check_in_time, only: :edit_check_in
  before_action :validate_check_out_time, only: :edit_check_out
  before_action :validate_is_start_of_week, only: :week

  def index
    set_week_variables(current_employee)
    @holiday_list_days = (Date.today..(Date.today + 60.days)).to_a
  end

  def week
    set_week_variables(current_employee)
    @holiday_list_days = (Date.today..(Date.today + 60.days)).to_a

    # renders the view for index so I don't need to create another view with
    # identicle content
    render :index
  end

  def edit_check_in
    @check_in = CheckIn.find(params[:id])

    check_in_date = Date.new(
      @check_in.check_in_time.year,
      @check_in.check_in_time.month,
      @check_in.check_in_time.day
    )

    additional_seconds = Time.parse(params[:check_in][:check_in_time]).seconds_since_midnight.seconds
    new_time = check_in_date.to_datetime + additional_seconds

    if (!@check_in.check_out_time || (new_time < @check_in.check_out_time)) && @check_in.update_attributes(check_in_time: new_time)
      flash[:success] = 'Time updated!'
    else
      flash[:danger] = 'Error updating time'
    end

    redirect_to request.referrer
  end

  def edit_check_out
    @check_in = CheckIn.find(params[:id])

    check_out_date = Date.new(
      @check_in.check_out_time.year,
      @check_in.check_out_time.month,
      @check_in.check_out_time.day
    )

    additional_seconds = Time.parse(params[:check_in][:check_out_time]).seconds_since_midnight.seconds
    new_time = check_out_date.to_datetime + additional_seconds

    if new_time < @check_in.check_in_time
      flash[:warning] = "You can't change the check in time to before the check out time."
    else
      if @check_in.update_attributes(check_out_time: new_time)
        flash[:success] = 'Time updated!'
      else
        flash[:danger] = 'Error updating time'
      end
    end

    redirect_to request.referrer
  end

  def mark_sick_day
    sick_day = current_employee.sick_days.build(date: params[:date])

    if current_employee.can_mark_as_sick_day?(Date.parse(params[:date]))
      if sick_day.save
        flash[:success] = 'Successfully marked as sick day.'
      else
        flash[:danger] = sick_day.errors.full_messages.first
      end
    else
      flash[:danger] = 'You cannot mark that day as a sick day.'
    end

    redirect_to request.referrer
  end

  private

    # Ensures the user enters a valid 24hour format, time
    def validate_check_in_time
      validate_time(params[:check_in][:check_in_time])
    end

    def validate_check_out_time
      validate_time(params[:check_in][:check_out_time])
    end

    def validate_time(user_entered_time)
      unless user_entered_time =~ /^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$/
        flash[:danger] = 'That is not a valid time!'
        redirect_to request.referrer
      end
    end

    def validate_is_start_of_week
      date = Date.parse(params[:start_of_week])

      unless date == date.at_beginning_of_week
        redirect_to week_path(start_of_week)
      end
    end
end

app/helpers/times_helper.rb
module TimesHelper
end

app/views/times/_check_in_form.html.haml
- if current_employee.checked_in?
  = form_for(CheckIn.new, url: check_out_path) do |f|
    = f.submit 'Check Out', class: 'btn btn-default btn-check-out'
- elsif !current_employee.can_check_in?(Date.today)
  = link_to 'Check In', '#', class: 'btn btn-disabled btn-check-out', disabled: 'disabled'
- else
  = form_for(CheckIn.new, url: check_in_path) do |f|
    = f.submit 'Check In', class: 'btn btn-primary btn-check-in'

app/views/times/_day.html.haml
- if current_employee.is_sick_day?(day)
  - if n == 0
    %td.table-check-in-times__td.-sick-day.center{ rowspan: current_employee.max_check_ins_on_week_starting(@start_of_week) }
      %strong Sick Day
- elsif CompanyHoliday.is_holiday?(day)
  - if n == 0
    %td.table-check-in-times__td.-company-holiday.center{ rowspan: current_employee.max_check_ins_on_week_starting(@start_of_week) }
      %strong Company Holiday
- elsif current_employee.is_on_holiday?(day)
  - if n == 0
    %td.table-check-in-times__td.-employee-holiday.center{ rowspan: current_employee.max_check_ins_on_week_starting(@start_of_week) }
      %strong You are on Holiday!
- else
  %td.table-check-in-times__td
    - if time
      %span.label.label-primary.label-time-table
        %span.glyphicon.glyphicon-log-in
        Check In

      = link_to time.check_in_time.strftime("%k:%M"), '#', class: 'table-check-in-times__time -link', title: 'Edit time', data: { toggle: :popover, check_in_id: time.id, check_in_type: 'check-in', placement: i > 2 ? :left : :right }

      %div{ class: "hidden-time-form #{time.id}-check-in", style: "display: none"}
        = form_for time, url: edit_time_check_in_path(time), html: { class: 'affix-time__form' } do |f|
          = f.text_field :check_in_time, value: time.check_in_time.strftime("%k:%M").strip, class: 'affix-time__form--text-field', pattern: '([01]?[0-9]|2[0-3]):[0-5][0-9]', title: 'Must be 24 hour format (HH:MM)'
          = f.submit 'Fix', class: 'btn btn-default pull-right affix-time__form--button'

      %br

      - if time.check_out_time
        %span.label.label-default.label-time-table
          %span.glyphicon.glyphicon-log-out
          Check Out

        = link_to time.check_out_time.strftime("%k:%M"), '#', class: 'table-check-in-times__time -link', title: 'Edit time', data: { toggle: :popover, check_in_id: time.id, check_in_type: 'check-out', placement: i > 2 ? :left : :right }

        %div{ class: "hidden-time-form #{time.id}-check-out", style: "display: none" }
          = form_for time, url: edit_time_check_out_path(time), html: { class: 'affix-time__form' } do |f|
            = f.text_field :check_out_time, value: time.check_out_time.strftime("%k:%M").strip, class: 'affix-time__form--text-field', pattern: '([01]?[0-9]|2[0-3]):[0-5][0-9]', title: 'Must be 24 hour format (HH:MM)'
            = f.submit 'Fix', class: 'btn btn-default pull-right affix-time__form--button'

app/views/times/_time_table.html.haml
%table.table.table-bordered.table-check-in-times
  %tbody
    %thead
      %tr.table-check-in-times__tr
        - @week.each do |day|
          %th.center.table-check-in-times__th
            - if current_employee.can_mark_as_sick_day?(day)
              %strong
                = link_to day.strftime('%A'), mark_sick_day_path(day), title: 'Mark as sick day', class: 'table-check-in-times__week-day', data: { toggle: :tooltip, placement: :top, confirm: 'Are you sure?' }
            - else
              %strong= day.strftime('%A')

            - if current_employee.all_check_ins_on_date(day).any?
              %span.label.label-default.label-time-logged-today
                = current_employee.formatted_time_checked_in_on_date(day)

    - current_employee.max_check_ins_on_week_starting(@start_of_week).times do |n|
      %tr.table-check-in-times__tr
        - @week.each_with_index do |day, i|
          = render 'times/day', time: @check_in_out_times[i][n], day: day, i: i, n: n
  %tfooter
    %tr
      %td.center{ colspan: 7 }
        Hours worked this week:
        %strong= current_employee.formatted_time_checked_in_on_week(@start_of_week)

app/views/times/index.html.haml
- provide :title, 'Check In'

.row
  .col-md-3
    = render 'shared/small_user_card', employee: current_employee

    = render 'shared/employee_holiday_list'

  .col-md-9
    = render 'check_in_form'

    %h5.center.week-starting
      .row
        .col-md-3.previous-week
          - if current_employee.can_view_previous_week?(@start_of_week)
            = link_to 'previous week', calendar_week_path(@start_of_week - 7.days), class: 'btn btn-primary'
          - else
            = link_to 'previous week', calendar_week_path(@start_of_week - 7.days), class: 'btn btn-disabled', disabled: ''

        .col-md-6.current-week
          = @start_of_week.strftime("%a #{@start_of_week.day.ordinalize} %B")
          &mdash;
          = @end_of_week.strftime("%a #{@end_of_week.day.ordinalize} %B")

        .col-md-3.next-week
          - if current_employee.can_view_next_week?(@start_of_week)
            = link_to 'next week', calendar_week_path(@start_of_week + 7.days), class: 'btn btn-primary'
          - else
            = link_to 'next week', calendar_week_path(@start_of_week + 7.days), class: 'btn btn-disabled', disabled: ''

    = render 'time_table'