config/routes.rb
Rails.application.routes.draw do

  devise_for :employees,
    path: '',
    path_names: { sign_in: 'login', sign_out: 'logout' }

  # Sets the 'index' action in the Times controller as the home page.
  root 'times#index'

  get 'week/:start_of_week', to: 'times#week', as: :calendar_week
  get 'sick-day/:date', to: 'times#mark_sick_day', as: :mark_sick_day

  post 'check-in', to: 'check_ins#check_in', as: :check_in
  post 'check-out', to: 'check_ins#check_out', as: :check_out

  resources :employees
  get 'employees/:id/:start_of_week', to: 'employees#week', as: :employee_calendar_week
  post 'employees/:id/deactivate-employee', to: 'employees#deactivate_employee', as: :deactivate_employee
  patch 'employees/:id/deactivate-employee', to: 'employees#deactivate_employee'

  resources :employee_holidays, path: 'holidays'

  resources :holiday_requests,  path: 'holiday-requests'
  get 'holiday-requests/:id/approve', to: 'holiday_requests#approve', as: :approve_holiday_request
  get 'holiday-requests/:id/decline', to: 'holiday_requests#decline', as: :decline_holiday_request

  resources :company_holidays, path: 'company-holidays'

  get 'calendar', to: 'calendar#index', as: :calendar
  get 'calendar/:date', to: 'calendar#month', as: :calendar_date

  # resources :times, only: %i(edit_check_in edit_check_out)
  patch 'times/:id/edit/check-in', to: 'times#edit_check_in', as: :edit_time_check_in
  patch 'times/:id/edit/check-out', to: 'times#edit_check_out', as: :edit_time_check_out
end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header.header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = image_tag('logo.png', class: 'header__logo')
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if employee_signed_in?
          - if current_employee.is_line_manager
            %li= link_to 'Company Holidays', company_holidays_path
            %li
              = link_to holiday_requests_path do
                Holiday Requests
                - if current_employee.pending_subordinate_holiday_requests.count > 0
                  %span.badge= current_employee.pending_subordinate_holiday_requests.count
            %li= link_to 'Employees', employees_path, class: 'header__right-space'

          %li= link_to 'Check In', root_path
          %li= link_to 'Holidays', employee_holidays_path
          %li= link_to 'Calendar', calendar_path

          %li.dropdown
            %a.header__dropdown.dropdown-toggle{ aria: { expanded: :false, haspopup: :true }, data: { toggle: :dropdown }, href: '#', role: :button }
              = image_tag current_employee.avatar.url, class: 'header__avatar'
              = current_employee.full_name
              %span.caret
            %ul.dropdown-menu
              %li= link_to 'Edit Details', edit_employee_registration_path
              %li.divider{ role: :separator }
              %li= link_to 'Log Out', destroy_employee_session_path, method: :delete

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? "Central &mdash; #{yield(:title)}".html_safe : "Central" %></title>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-daterangepicker/2.1.19/daterangepicker.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %> <%= controller.action_name %>">

<%= render 'layouts/header' if header_should_be_displayed %>

<div class="container">
  <%= render 'shared/flash_notice' unless on_page('sessions', 'new') || on_page('registrations', 'new') %>
  <%= yield %>
</div>

<%= javascript_include_tag 'application' %>

</body>
</html>